name: 'kick-action'
description: 'Github action that installs and runs a kick command'
author: 'udoprog'

inputs:
  version:
    description: 'Version of kick to install. Defaults to "latest".'
    default: 'latest'

runs:
  using: 'node16'
  main: 'dist/index.js'

branding:
  icon: 'package'
  color: 'orange'
