name: Test

on:
  push:
    branches:
    - test

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: udoprog/kick@nightly
    - run: kick --help

  windows:
    runs-on: windows-latest
    steps:
    - uses: udoprog/kick@nightly
    - run: kick --help
