name: Weekly

on:
  schedule:
    - cron: '53 2 * * 2'

jobs:
  weekly:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        rust: ['1.74', stable]
        os: [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{matrix.rust}}
    - run: cargo build --workspace
